In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
# write your code here ^_^
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [6]:
# write your code here ^_^
y =np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [10]:
# write your code here ^_^
np.add(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [13]:
# write your code here ^_^
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(3, 3)
9
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [26]:
# write your code here ^_^
w = np.array(
[[11,12],[13,14],[15,16]]
)
print(w)
print(w.shape)

[[11 12]
 [13 14]
 [15 16]]
(3, 2)


## Q#6: Create z array contains the numbers from 1 to 3.

In [44]:
# write your code here ^_^
z = np.array([1, 2, 3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [55]:
# write your code here ^_^

z_reshaped = z.reshape(-1, 1) 
newArray = np.hstack((z_reshaped, w))
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [47]:
# write your code here ^_^
for row in newArray:
    for item in row:
        print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [48]:
# write your code here ^_^
Reverse = []
 
# looping through matrix_1 and appending matrix_2
for i in range(len(newArray)):
    Reverse.append(newArray[i][::-1])
 
print('Matrix before changing column order:\n')
for rows in newArray:
    print(rows)
print('\nMatrix after changing column order:\n')
for rows in Reverse:
    print(rows)

Matrix before changing column order:

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]

Matrix after changing column order:

[12 11  1]
[14 13  2]
[16 15  3]


## Q#10: Decrement all elements of "newArray" with 1.

In [50]:
# write your code here ^_^
newArray = newArray -1
newArray

array([[-1,  9, 10],
       [ 0, 11, 12],
       [ 1, 13, 14]])

## Q#11: Find smallest and biggest values in "newArray".

In [51]:
# write your code here ^_^
print (np.max(newArray))
print (np.min(newArray))

14
-1


## Q#12: Print the first row of "newArray" using indexing.

In [56]:
# write your code here ^_^

row = newArray[0,:]
row

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [64]:
# write your code here ^_^
value_12 = newArray[0, 2]
print("Value 12:", value_12)

Value 12: 12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [70]:
# write your code here ^_^
print (newArray)
value_13 = newArray[1,1 ]
print("Value 13:", value_13)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]
Value 13: 13


## Q#15: Change the shape of "newArray" to (9,1).

In [76]:
# write your code here ^_^
newArray1=newArray.reshape(9,1)
print (newArray1)
print (newArray)

[[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]
[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#16: Change the shape of "newArray" to (3,2).

In [85]:
# write your code here ^_^

newArray=newArray.reshape(9,1)
print (newArray)

newArray1=newArray.reshape(3,3)
print (newArray)

[[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]
[[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]


# Well Done 🎉