In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [5]:
# write your code here ^_^

x= np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [7]:
# write your code here ^_^
y=np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [8]:
# write your code here ^_^
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [12]:
# write your code here ^_^

x.dtype

x.ndim

x.shape

x.size


dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [19]:
# write your code here ^_^
w=np.array([
    
    [11,12],[13,14],[15,16]

])
w

# another way

w1= np.arange(11,17).reshape(3,2)
w1

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [44]:
# write your code here ^_^

z= np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [71]:
# write your code here ^_^

newArray= np.column_stack((w,z))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [56]:
# write your code here ^_^

for i in newArray:
     for item in i:
        print(item)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [64]:
# write your code here ^_^

newArray_reverse =newArray.transpose()
newArray_reverse

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [65]:
# write your code here ^_^

newArray_reverse -= 1
newArray_reverse

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [67]:
# write your code here ^_^
newArray_reverse.min()

newArray_reverse.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [74]:
# write your code here ^_^

newArray_reverse[0]

array([10, 12, 14])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [73]:
# write your code here ^_^
newArray_reverse
newArray_reverse[0,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [78]:
# write your code here ^_^
print(newArray_reverse[2,0])
print(newArray_reverse[1,1])


0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [82]:
# write your code here ^_^


newArray_reverse.reshape(-1,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [87]:
# write your code here ^_^

z2=newArray_reverse.reshape(1,-1)
z2.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉