In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
# write your code here ^_^
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [3]:
# write your code here ^_^
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [4]:
# write your code here ^_^
x + y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
# write your code here ^_^
print("the dimension of x is " , x.ndim)
print("the shape of x is ",x.shape)
print("the size of x is " ,x.size)
print("the type of x is " ,x.dtype)

the dimension of x is  2
the shape of x is  (3, 3)
the size of x is  9
the type of x is  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])


## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
# write your code here ^_^
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
# write your code here ^_^
newArray= np.column_stack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
# write your code here ^_^

for i in newArray.ravel():
    print(i)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
# write your code here ^_^
newArray=newArray.transpose()
newArray

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
# write your code here ^_^
newArray -= 1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
# write your code here ^_^
SnewArray =newArray.min()
BnewArray =newArray.max()

In [13]:
SnewArray

0

In [14]:
BnewArray

15

## Q#12: Print the first row of "newArray" using indexing.

In [15]:
# write your code here ^_^
newArray[0:1]


array([[0, 1, 2]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [17]:
# write your code here ^_^
newArray_12 = newArray[newArray == 12] 
newArray_12

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [26]:
# write your code here ^_^

print(newArray[newArray == 0 ] )
print( newArray[newArray == 13] )


[0]
[13]


## Q#15: Change the shape of "newArray" to (9,1).

In [28]:
# write your code here ^_^
newArray= newArray.reshape(9,1)
newArray

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [12],
       [14],
       [11],
       [13],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [29]:
# write your code here ^_^
newArray = newArray.reshape(3,2)
newArray

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉