In [177]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [178]:
# write your code here ^_^
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [179]:
# write your code here ^_^
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [180]:
# write your code here ^_^
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [181]:
np.add(x, y) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [182]:
# write your code here ^_^
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (3, 3)
size =  9


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [183]:
# write your code here ^_^
w = np.array(
    [
        [11, 12], 
        [13, 14],
        [15, 16]
    ])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [184]:
# write your code here ^_^
z = np.array(
    [[1,2,3],
     [1,2,3]
    ])
z

array([[1, 2, 3],
       [1, 2, 3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [185]:
# write your code here ^_^
w.shape = (2, 3)
w

array([[11, 12, 13],
       [14, 15, 16]])

In [186]:
newArray = np.hstack((w,z))
newArray

array([[11, 12, 13,  1,  2,  3],
       [14, 15, 16,  1,  2,  3]])

In [187]:
newArray.shape = (4, 3)
newArray

array([[11, 12, 13],
       [ 1,  2,  3],
       [14, 15, 16],
       [ 1,  2,  3]])

In [188]:
newArray= np.delete(newArray, 1, 0)
newArray

array([[11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [189]:
# write your code here ^_^
for item in newArray.flat:
    print(item)

11
12
13
14
15
16
1
2
3


## Q#9: Reverse the columns and rows of "newArray".

In [190]:
# write your code here ^_^
np.column_stack((w,z))

array([[11, 12, 13,  1,  2,  3],
       [14, 15, 16,  1,  2,  3]])

In [191]:
np.row_stack((w,z))

array([[11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 1,  2,  3]])

In [192]:
np.flipud(newArray)

array([[ 1,  2,  3],
       [14, 15, 16],
       [11, 12, 13]])

In [193]:
newArray.transpose()

array([[11, 14,  1],
       [12, 15,  2],
       [13, 16,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [194]:
# write your code here ^_^
newArray-=1
newArray

array([[10, 11, 12],
       [13, 14, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [195]:
# write your code here ^_^
newArray.min()

0

In [196]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [197]:
# write your code here ^_^
newArray[0,:]

array([10, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [198]:
# write your code here ^_^
newArray[0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [199]:
# write your code here ^_^
newArray[[2,1],0]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [200]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [201]:
newArray= np.delete(newArray, 1, 0)
newArray

array([[10, 11, 12],
       [ 0,  1,  2]])

In [202]:
# write your code here ^_^
newArray.reshape(3,2)

array([[10, 11],
       [12,  0],
       [ 1,  2]])

# Well Done 🎉