In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
# write your code here ^_^
x = np.array([1])

## Q#2: Create y array with elements equal to 0.

In [5]:
# write your code here ^_^
y = np.array([0])

## Q#3: Add x and y arrays.

In [6]:
# write your code here ^_^
x + y

array([1])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [15]:
# write your code here ^_^
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x.size)


(1,)
int32
1
1


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [55]:
# write your code here ^_^
w = np.array([[11,12],
        [13,14],
        [15,16]])
w



array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [52]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [79]:
# write your code here ^_^
z1 =z.reshape(3,1)
z1

newArray = np.hstack((z1,w)) 
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [90]:
# write your code here ^_^
for row in newArray :
    for number in row :
        print (number)
    

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [81]:
# write your code here ^_^
newArray.transpose()


array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [70]:
# write your code here ^_^
newArray -=1
newArray

array([[-1,  9, 10],
       [ 0, 11, 12],
       [ 1, 13, 14]])

## Q#11: Find smallest and biggest values in "newArray".

In [72]:
# write your code here ^_^
newArray.min()
newArray.max()

14

## Q#12: Print the first row of "newArray" using indexing.

In [73]:
# write your code here ^_^
newArray[0,:]

array([-1,  9, 10])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [74]:
# write your code here ^_^
newArray[1][2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [94]:
# write your code here ^_^
newArray[1][0]
newArray[2][1]


15

## Q#15: Change the shape of "newArray" to (9,1).

In [86]:
# write your code here ^_^
newArray.reshape(9,1)

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [95]:
# write your code here ^_^
 #

# Well Done 🎉