In [36]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [37]:
# write your code here ^_^

x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [38]:
# write your code here ^_^
y=np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [39]:
# write your code here ^_^
np.add(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [40]:
# write your code here ^_^
print("Number of dimernsion = ",x.ndim)
print("Shape =  ",x.shape)
print("size = ",x.size)
print("Type = ",x.dtype)

Number of dimernsion =  2
Shape =   (3, 3)
size =  9
Type =  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [61]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]])
w.shape

(3, 2)

## Q#6: Create z array contains the numbers from 1 to 3.

In [83]:
# write your code here ^_^
z=np.arange(1,4).reshape((-1,1))
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [116]:
# write your code here ^_^
newArray=np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [91]:
# write your code here ^_^
for n in newArray.flat:
    print(n)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [117]:
# write your code here ^_^
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [118]:
newArray # before

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [119]:
# write your code here ^_^
newArray=newArray-1 # After
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [104]:
# write your code here ^_^
print("Smallest = ",newArray.min())
print("biggest = ",newArray.max())

Smallest =  1
biggest =  16


## Q#12: Print the first row of "newArray" using indexing.

In [106]:
newArray # All

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [109]:
# write your code here ^_^
newArray[0] # First Row

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [112]:
# write your code here ^_^
newArray[0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [120]:
# write your code here ^_^
newArray[0,0]

0

## Q#15: Change the shape of "newArray" to (9,1).

In [121]:
# write your code here ^_^
newArray.reshape((9,1))

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [137]:
# write your code here ^_^
np.resize(newArray,new_shape=(3,2))

## Error

array([[ 0, 10],
       [11,  1],
       [12, 13]])

# Well Done 🎉