In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [8]:
# write your code here ^_^
x=np.ones((4,4))

## Q#2: Create y array with elements equal to 0.

In [9]:
# write your code here ^_^
y= np.zeros((4,4))

## Q#3: Add x and y arrays.

In [11]:
# write your code here ^_^
Z= x+y
Z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
# write your code here ^_^

print(f"Type: {x.dtype}")
print(f"Dimension: {x.ndim}")
print(f"Shape: {x.shape}")
print(f"Size: {x.size}")

Type: float64
Dimension: 2
Shape: (4, 4)
Size: 16


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [37]:
# write your code here ^_^
w =np.array([[11,12],
             [13,14],
             [15,16]]) 
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [38]:
# write your code here ^_^

z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [53]:
# write your code here ^_^
z=z.reshape(-1,1) 
newArray = np.hstack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [48]:
# write your code here ^_^
for lst in newArray:
    for items in lst:
        print(items)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [50]:
# write your code here ^_^
rev_newArray = np.flip(newArray, axis=0)  
rev_newArray = np.flip(rev_newArray, axis=1) 
rev_newArray


array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [54]:
# write your code here ^_^
newArray-=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [56]:
# write your code here ^_^
print(f"smallest:{newArray.min()}")
print(f"biggest:{newArray.max()}")

smallest:0
biggest:15


## Q#12: Print the first row of "newArray" using indexing.

In [60]:
# write your code here ^_^
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [73]:
# write your code here ^_^
print(newArray[1][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [77]:
# write your code here ^_^
print(newArray[0][0])
print(newArray[1][2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [84]:
# write your code here ^_^
newArray=newArray.reshape(9,1)
newArray



array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [87]:
# write your code here ^_^
#it is not possible to reshape a size 9 to (3,2)
#as you can see the error
newArray =newArray.reshape(3,2)
newArray

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉