In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
# write your code here ^_^
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [9]:
# write your code here ^_^
y=np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [10]:
# write your code here ^_^
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
# write your code here ^_^
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (3, 3)
size =  9


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [24]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [30]:
# write your code here ^_^
z=np.array([1,2,3])
z.reshape(3,1)

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [33]:
# write your code here ^_^
newArray=np.hstack((w,z.reshape(3,1)))


## Q#8: Print all elements of "newArray" using the loop.

In [34]:
# write your code here ^_^
for item in newArray:
    print(item)

[11 12  1]
[13 14  2]
[15 16  3]


## Q#9: Reverse the columns and rows of "newArray".

In [35]:
# write your code here ^_^
np.transpose(newArray)

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [39]:
# write your code here ^_^
newArray-=1
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [40]:
# write your code here ^_^
np.min(newArray)

0

## Q#12: Print the first row of "newArray" using indexing.

In [143]:
# write your code here ^_^
print(newArray[0])
#or
print(newArray[0,:])

[10 11  0]
[10 11  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [113]:
# write your code here ^_^
newArray[1,0]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [347]:
# write your code here ^_^

newArray[[0,1],[2,1]]

array([ 0, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [345]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [11],
       [ 0],
       [12],
       [13],
       [ 1],
       [14],
       [15],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [346]:
# write your code here ^_^
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉