In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [3]:
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [4]:
np.add(x, y) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (3, 3)
size =  9


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
w = np.array(
    [
    [11,12],
    [13,14],
    [15,16]
    ])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
newArray = np.hstack((z,w.ravel())).reshape(3,3) # horizontal stacking
newArray

array([[ 1,  2,  3],
       [11, 12, 13],
       [14, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
for i in newArray:
    print(i)

[1 2 3]
[11 12 13]
[14 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
newArray = newArray.transpose()
newArray

array([[ 1, 11, 14],
       [ 2, 12, 15],
       [ 3, 13, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
newArray -= 1
newArray

array([[ 0, 10, 13],
       [ 1, 11, 14],
       [ 2, 12, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
print('The smallest value in "newArray" = ', newArray.min())
print('The biggest value in "newArray" = ', newArray.max())

The smallest value in "newArray" =  0
The biggest value in "newArray" =  15


## Q#12: Print the first row of "newArray" using indexing.

In [13]:
newArray[0,:]

array([ 0, 10, 13])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
newArray[2,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [17]:
print(newArray[0,0] , newArray[0,2])

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [18]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [13],
       [ 1],
       [11],
       [14],
       [ 2],
       [12],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [19]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉